# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dst_swig', [dirname(__file__)])
        except ImportError:
            import _dst_swig
            return _dst_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_dst_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _dst_swig = swig_import_helper()
    del swig_import_helper
else:
    import _dst_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    """Proxy of C++ swig::SwigPyIterator class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dst_swig.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self):
        """value(self) -> PyObject"""
        return _dst_swig.SwigPyIterator_value(self)

    def incr(self, n = 1):
        """incr(self, size_t n = 1) -> SwigPyIterator"""
        return _dst_swig.SwigPyIterator_incr(self, n)

    def decr(self, n = 1):
        """decr(self, size_t n = 1) -> SwigPyIterator"""
        return _dst_swig.SwigPyIterator_decr(self, n)

    def distance(self, *args, **kwargs):
        """distance(self, SwigPyIterator x) -> ptrdiff_t"""
        return _dst_swig.SwigPyIterator_distance(self, *args, **kwargs)

    def equal(self, *args, **kwargs):
        """equal(self, SwigPyIterator x) -> bool"""
        return _dst_swig.SwigPyIterator_equal(self, *args, **kwargs)

    def copy(self):
        """copy(self) -> SwigPyIterator"""
        return _dst_swig.SwigPyIterator_copy(self)

    def next(self):
        """next(self) -> PyObject"""
        return _dst_swig.SwigPyIterator_next(self)

    def __next__(self):
        """__next__(self) -> PyObject"""
        return _dst_swig.SwigPyIterator___next__(self)

    def previous(self):
        """previous(self) -> PyObject"""
        return _dst_swig.SwigPyIterator_previous(self)

    def advance(self, *args, **kwargs):
        """advance(self, ptrdiff_t n) -> SwigPyIterator"""
        return _dst_swig.SwigPyIterator_advance(self, *args, **kwargs)

    def __eq__(self, *args, **kwargs):
        """__eq__(self, SwigPyIterator x) -> bool"""
        return _dst_swig.SwigPyIterator___eq__(self, *args, **kwargs)

    def __ne__(self, *args, **kwargs):
        """__ne__(self, SwigPyIterator x) -> bool"""
        return _dst_swig.SwigPyIterator___ne__(self, *args, **kwargs)

    def __iadd__(self, *args, **kwargs):
        """__iadd__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _dst_swig.SwigPyIterator___iadd__(self, *args, **kwargs)

    def __isub__(self, *args, **kwargs):
        """__isub__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _dst_swig.SwigPyIterator___isub__(self, *args, **kwargs)

    def __add__(self, *args, **kwargs):
        """__add__(self, ptrdiff_t n) -> SwigPyIterator"""
        return _dst_swig.SwigPyIterator___add__(self, *args, **kwargs)

    def __sub__(self, *args):
        """
        __sub__(self, ptrdiff_t n) -> SwigPyIterator
        __sub__(self, SwigPyIterator x) -> ptrdiff_t
        """
        return _dst_swig.SwigPyIterator___sub__(self, *args)

    def __iter__(self): return self
SwigPyIterator_swigregister = _dst_swig.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class dst_fcch_sptr(object):
    """Proxy of C++ boost::shared_ptr<(dst_fcch)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> dst_fcch_sptr
        __init__(self,  p) -> dst_fcch_sptr
        """
        this = _dst_swig.new_dst_fcch_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(self)"""
        return _dst_swig.dst_fcch_sptr___deref__(self)

    __swig_destroy__ = _dst_swig.delete_dst_fcch_sptr
    __del__ = lambda self : None;
    def rho(self):
        """
        rho(self) -> double

        Params: (NONE)
        """
        return _dst_swig.dst_fcch_sptr_rho(self)

    def set_rho(self, *args, **kwargs):
        """
        set_rho(self, double rho)

        Params: (rho)
        """
        return _dst_swig.dst_fcch_sptr_set_rho(self, *args, **kwargs)

    def G(self):
        """
        G(self) -> double

        Params: (NONE)
        """
        return _dst_swig.dst_fcch_sptr_G(self)

    def set_G(self, *args, **kwargs):
        """
        set_G(self, double G)

        Params: (G)
        """
        return _dst_swig.dst_fcch_sptr_set_G(self, *args, **kwargs)

    def D(self):
        """
        D(self) -> int

        Params: (NONE)
        """
        return _dst_swig.dst_fcch_sptr_D(self)

    def set_D(self, *args, **kwargs):
        """
        set_D(self, double D)

        Params: (D)
        """
        return _dst_swig.dst_fcch_sptr_set_D(self, *args, **kwargs)

    def taps(self):
        """
        taps(self) -> int

        Params: (NONE)
        """
        return _dst_swig.dst_fcch_sptr_taps(self)

    def set_taps(self, *args, **kwargs):
        """
        set_taps(self, double taps)

        Params: (taps)
        """
        return _dst_swig.dst_fcch_sptr_set_taps(self, *args, **kwargs)

    def general_work(self, *args, **kwargs):
        """
        general_work(self, int noutput_items, gr_vector_int ninput_items, gr_vector_const_void_star input_items, 
            gr_vector_void_star output_items) -> int

        Params: (noutput_items, ninput_items, input_items, output_items)
        """
        return _dst_swig.dst_fcch_sptr_general_work(self, *args, **kwargs)

    def history(self):
        """history(self) -> unsigned int"""
        return _dst_swig.dst_fcch_sptr_history(self)

    def output_multiple(self):
        """output_multiple(self) -> int"""
        return _dst_swig.dst_fcch_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(self) -> double"""
        return _dst_swig.dst_fcch_sptr_relative_rate(self)

    def start(self):
        """start(self) -> bool"""
        return _dst_swig.dst_fcch_sptr_start(self)

    def stop(self):
        """stop(self) -> bool"""
        return _dst_swig.dst_fcch_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(self, unsigned int which_input) -> uint64_t"""
        return _dst_swig.dst_fcch_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(self, unsigned int which_output) -> uint64_t"""
        return _dst_swig.dst_fcch_sptr_nitems_written(self, *args, **kwargs)

    def detail(self):
        """detail(self) -> gr_block_detail_sptr"""
        return _dst_swig.dst_fcch_sptr_detail(self)

    def set_detail(self, *args, **kwargs):
        """set_detail(self, gr_block_detail_sptr detail)"""
        return _dst_swig.dst_fcch_sptr_set_detail(self, *args, **kwargs)

    def name(self):
        """name(self) -> string"""
        return _dst_swig.dst_fcch_sptr_name(self)

    def input_signature(self):
        """input_signature(self) -> gr_io_signature_sptr"""
        return _dst_swig.dst_fcch_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(self) -> gr_io_signature_sptr"""
        return _dst_swig.dst_fcch_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(self) -> long"""
        return _dst_swig.dst_fcch_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(self) -> gr_basic_block_sptr"""
        return _dst_swig.dst_fcch_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(self, int ninputs, int noutputs) -> bool"""
        return _dst_swig.dst_fcch_sptr_check_topology(self, *args, **kwargs)

dst_fcch_sptr_swigregister = _dst_swig.dst_fcch_sptr_swigregister
dst_fcch_sptr_swigregister(dst_fcch_sptr)

dst_fcch_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id ())


def fcch(rho = 0.03125, G = 0.08, D = 5, taps = 17):
  """
    fcch(double rho = 0.03125, double G = 0.08, int D = 5, int taps = 17) -> dst_fcch_sptr

    <+description+>

    Params: (rho, G, D, taps)
    """
  return _dst_swig.fcch(rho, G, D, taps)
class dst_fcchsync_sptr(object):
    """Proxy of C++ boost::shared_ptr<(dst_fcchsync)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> dst_fcchsync_sptr
        __init__(self,  p) -> dst_fcchsync_sptr
        """
        this = _dst_swig.new_dst_fcchsync_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(self)"""
        return _dst_swig.dst_fcchsync_sptr___deref__(self)

    __swig_destroy__ = _dst_swig.delete_dst_fcchsync_sptr
    __del__ = lambda self : None;
    def rho(self):
        """
        rho(self) -> double

        Params: (NONE)
        """
        return _dst_swig.dst_fcchsync_sptr_rho(self)

    def set_osr(self, *args, **kwargs):
        """
        set_osr(self, int osr)

        Params: (osr)
        """
        return _dst_swig.dst_fcchsync_sptr_set_osr(self, *args, **kwargs)

    def set_rho(self, *args, **kwargs):
        """
        set_rho(self, double rho)

        Params: (rho)
        """
        return _dst_swig.dst_fcchsync_sptr_set_rho(self, *args, **kwargs)

    def G(self):
        """
        G(self) -> double

        Params: (NONE)
        """
        return _dst_swig.dst_fcchsync_sptr_G(self)

    def set_G(self, *args, **kwargs):
        """
        set_G(self, double G)

        Params: (G)
        """
        return _dst_swig.dst_fcchsync_sptr_set_G(self, *args, **kwargs)

    def D(self):
        """
        D(self) -> int

        Params: (NONE)
        """
        return _dst_swig.dst_fcchsync_sptr_D(self)

    def fsamp(self):
        """
        fsamp(self) -> int

        Params: (NONE)
        """
        return _dst_swig.dst_fcchsync_sptr_fsamp(self)

    def set_D(self, *args, **kwargs):
        """
        set_D(self, double D)

        Params: (D)
        """
        return _dst_swig.dst_fcchsync_sptr_set_D(self, *args, **kwargs)

    def taps(self):
        """
        taps(self) -> int

        Params: (NONE)
        """
        return _dst_swig.dst_fcchsync_sptr_taps(self)

    def set_taps(self, *args, **kwargs):
        """
        set_taps(self, double taps)

        Params: (taps)
        """
        return _dst_swig.dst_fcchsync_sptr_set_taps(self, *args, **kwargs)

    def calculate_fcch_firale(self, *args, **kwargs):
        """
        calculate_fcch_firale(self, int noutput_items, gr_complex input_buffer, gr_complex out_buffer, 
            gr_complex offset, std::vector<(gr_complex,std::allocator<(gr_complex)>)> taps_buffer, 
            __dummy_5__ eavg_buffer, 
            double alpha, 
            double d_rho, double d_G, int d_D, int d_taps)

        Params: (noutput_items, input_buffer, out_buffer, offset, taps_buffer, eavg_buffer, alpha, d_rho, d_G, d_D, d_taps)
        """
        return _dst_swig.dst_fcchsync_sptr_calculate_fcch_firale(self, *args, **kwargs)

    def work(self, *args, **kwargs):
        """
        work(self, int noutput_items, gr_vector_const_void_star input_items, 
            gr_vector_void_star output_items) -> int

        Params: (noutput_items, input_items, output_items)
        """
        return _dst_swig.dst_fcchsync_sptr_work(self, *args, **kwargs)

    def history(self):
        """history(self) -> unsigned int"""
        return _dst_swig.dst_fcchsync_sptr_history(self)

    def output_multiple(self):
        """output_multiple(self) -> int"""
        return _dst_swig.dst_fcchsync_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(self) -> double"""
        return _dst_swig.dst_fcchsync_sptr_relative_rate(self)

    def start(self):
        """start(self) -> bool"""
        return _dst_swig.dst_fcchsync_sptr_start(self)

    def stop(self):
        """stop(self) -> bool"""
        return _dst_swig.dst_fcchsync_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(self, unsigned int which_input) -> uint64_t"""
        return _dst_swig.dst_fcchsync_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(self, unsigned int which_output) -> uint64_t"""
        return _dst_swig.dst_fcchsync_sptr_nitems_written(self, *args, **kwargs)

    def detail(self):
        """detail(self) -> gr_block_detail_sptr"""
        return _dst_swig.dst_fcchsync_sptr_detail(self)

    def set_detail(self, *args, **kwargs):
        """set_detail(self, gr_block_detail_sptr detail)"""
        return _dst_swig.dst_fcchsync_sptr_set_detail(self, *args, **kwargs)

    def name(self):
        """name(self) -> string"""
        return _dst_swig.dst_fcchsync_sptr_name(self)

    def input_signature(self):
        """input_signature(self) -> gr_io_signature_sptr"""
        return _dst_swig.dst_fcchsync_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(self) -> gr_io_signature_sptr"""
        return _dst_swig.dst_fcchsync_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(self) -> long"""
        return _dst_swig.dst_fcchsync_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(self) -> gr_basic_block_sptr"""
        return _dst_swig.dst_fcchsync_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(self, int ninputs, int noutputs) -> bool"""
        return _dst_swig.dst_fcchsync_sptr_check_topology(self, *args, **kwargs)

dst_fcchsync_sptr_swigregister = _dst_swig.dst_fcchsync_sptr_swigregister
dst_fcchsync_sptr_swigregister(dst_fcchsync_sptr)

dst_fcchsync_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id ())

fcch_len = _dst_swig.fcch_len

def fcchsync(rho = 0.03125, G = 0.08, D = 5, taps = 17, osr = 4, 
    fsamp = 1083333):
  """
    fcchsync(double rho = 0.03125, double G = 0.08, int D = 5, int taps = 17, 
        int osr = 4, int fsamp = 1083333) -> dst_fcchsync_sptr

    Calculates the Freqency offset of a GSM system by searching the FCCH <+description+>

    Params: (rho, G, D, taps, osr, fsamp)
    """
  return _dst_swig.fcchsync(rho, G, D, taps, osr, fsamp)
class dst_sch_sptr(object):
    """Proxy of C++ boost::shared_ptr<(dst_sch)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(self) -> dst_sch_sptr
        __init__(self,  p) -> dst_sch_sptr
        """
        this = _dst_swig.new_dst_sch_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(self)"""
        return _dst_swig.dst_sch_sptr___deref__(self)

    __swig_destroy__ = _dst_swig.delete_dst_sch_sptr
    __del__ = lambda self : None;
    def set_osr(self, *args, **kwargs):
        """
        set_osr(self, int osr)

        Params: (osr)
        """
        return _dst_swig.dst_sch_sptr_set_osr(self, *args, **kwargs)

    def work(self, *args, **kwargs):
        """
        work(self, int noutput_items, gr_vector_const_void_star input_items, 
            gr_vector_void_star output_items) -> int

        Params: (noutput_items, input_items, output_items)
        """
        return _dst_swig.dst_sch_sptr_work(self, *args, **kwargs)

    def history(self):
        """history(self) -> unsigned int"""
        return _dst_swig.dst_sch_sptr_history(self)

    def output_multiple(self):
        """output_multiple(self) -> int"""
        return _dst_swig.dst_sch_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(self) -> double"""
        return _dst_swig.dst_sch_sptr_relative_rate(self)

    def start(self):
        """start(self) -> bool"""
        return _dst_swig.dst_sch_sptr_start(self)

    def stop(self):
        """stop(self) -> bool"""
        return _dst_swig.dst_sch_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(self, unsigned int which_input) -> uint64_t"""
        return _dst_swig.dst_sch_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(self, unsigned int which_output) -> uint64_t"""
        return _dst_swig.dst_sch_sptr_nitems_written(self, *args, **kwargs)

    def detail(self):
        """detail(self) -> gr_block_detail_sptr"""
        return _dst_swig.dst_sch_sptr_detail(self)

    def set_detail(self, *args, **kwargs):
        """set_detail(self, gr_block_detail_sptr detail)"""
        return _dst_swig.dst_sch_sptr_set_detail(self, *args, **kwargs)

    def name(self):
        """name(self) -> string"""
        return _dst_swig.dst_sch_sptr_name(self)

    def input_signature(self):
        """input_signature(self) -> gr_io_signature_sptr"""
        return _dst_swig.dst_sch_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(self) -> gr_io_signature_sptr"""
        return _dst_swig.dst_sch_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(self) -> long"""
        return _dst_swig.dst_sch_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(self) -> gr_basic_block_sptr"""
        return _dst_swig.dst_sch_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(self, int ninputs, int noutputs) -> bool"""
        return _dst_swig.dst_sch_sptr_check_topology(self, *args, **kwargs)

dst_sch_sptr_swigregister = _dst_swig.dst_sch_sptr_swigregister
dst_sch_sptr_swigregister(dst_sch_sptr)

dst_sch_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id ())


def sch(osr = 4):
  """
    sch(int osr = 4) -> dst_sch_sptr

    <+description+>

    Params: (osr)
    """
  return _dst_swig.sch(osr)


